### ISSUE TITLE
Data Scraping for Companies Details and Reviews

### ISSUE THREAD

**Issue by junweilam** [junweilam/ITP_SE_14#4]

**Comment by RyujiRoarar99** [comment]
Able to scrap overviews

[YMCA_reviews.xlsx](https://github.com/junweilam/ITP_SE_14/files/11646007/YMCA_reviews.xlsx)

**Comment by RyujiRoarar99** [comment]
Able to scrap overview

[YMCA.xlsx](https://github.com/junweilam/ITP_SE_14/files/11646009/YMCA.xlsx)
